In [2]:
import pandas as pd
import numpy as np

In [4]:
# 1. Simple dict — keys become columns
d = {'name': ['Alice', 'Bob'], 'age': [30, 25]}
pd.DataFrame(d)

    name  age
0  Alice   30
1    Bob   25

In [7]:
# 2. Dict of scalars — use .items() for key-value pairs
d = {'CA': 'West', 'NY': 'East', 'TX': 'South'}
pd.DataFrame(d.items(), columns=['state', 'region'])

  state region
0    CA   West
1    NY   East
2    TX  South

In [9]:
# 3. List of dicts — each dict becomes a row
d = [{'name': 'Alice', 'age': 30}, {'name': 'Bob', 'age': 25}]
pd.DataFrame(d)

    name  age
0  Alice   30
1    Bob   25

In [35]:
# 4. Nested dict — outer keys become columns, inner keys become index
d = {'Alice': {'math': 90, 'english': 85}, 'Bob': {'math': 70, 'english': 95}}
df = pd.DataFrame(d)
df

         Alice  Bob
math        90   70
english     85   95

In [40]:
for i, row in df.iterrows():
    print (row['Alice'])
    print (row.Alice)
    print ('i=',i)

90
90
i= math
85
85
i= english

In [28]:
d.get(list(d.keys())[0])

{'math': 90, 'english': 85}

In [29]:
d.items()

dict_items([('Alice', {'math': 90, 'english': 85}), ('Bob', {'math': 70, 'english': 95})])

In [30]:
d

{'Alice': {'math': 90, 'english': 85}, 'Bob': {'math': 70, 'english': 95}}