# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Create a data dictionary that looks like the DataFrame below

In [5]:
data_0 = {
    'evolution': ['Ivysaur','Charmeleon','Wartotle','Metapod'],
    'hp': [45,39,44,45],
    'name': ['Bulbasaur','Charmander','Squirtle','Caterpie'],
    'pokedex': ['yes','no','yes','no'],
    'type': ['grass','fire','water','bug'],
}

### Step 3. Assign it to a variable called pokemon

In [7]:
pokemon = pd.DataFrame(data_0)
pokemon

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  grass
1  Charmeleon  39  Charmander      no   fire
2    Wartotle  44    Squirtle     yes  water
3     Metapod  45    Caterpie      no    bug

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

### Step 5. Add another column called place, and insert what you have in mind.

In [8]:
pokemon['place'] = ['park','woods','ocean','river']

### Step 6. Present the type of each column

In [12]:
pokemon.dtypes

evolution      str
hp           int64
name           str
pokedex        str
type           str
place          str
dtype: object

In [14]:
pokemon.select_dtypes(['str','int'])

    evolution  hp        name pokedex   type  place
0     Ivysaur  45   Bulbasaur     yes  grass   park
1  Charmeleon  39  Charmander      no   fire  woods
2    Wartotle  44    Squirtle     yes  water  ocean
3     Metapod  45    Caterpie      no    bug  river

### BONUS: Create your own question and answer it.